name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Verify README generation
        uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v1
        with:
          project_status: incubating
          project_stability: alpha
          project_type: other
          sdk_language: Go
          template_file: ./README.template.md
          output_file: ./README.md
          dev_docs_slug: go

