name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Verify README generation
        uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v1
        with:
          project_status: incubating
          project_stability: experimental
          project_type: other
          sdk_language: Go
          output_file: ./README.md
  test:
    needs: [ readme ]
    uses: ./.github/workflows/test.yml
    secrets:
      auth-token: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      github-token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }

